config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  get 'pages/home'

  get 'pages/about'

  get 'pages/articles'

  get 'home/index'

  resources :articles
  
  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end


  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    @article = Article.new(article_params)
   
   if @article.save
      # redirect to index action
      flash[:notice] = "Article was saved successfully"
      redirect_to articles_path 
    else
      flash.now[:error] = "There was a problem saving this Article"
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])

  end

  def update
  @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @article = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Articles</h1>
<%= render 'form' %>
<td><%= link_to 'Delete', article_path(@article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

app/views/articles/index.html.erb
<h1>Articles</h1>
 
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
 

app/views/articles/show.html.erb
<div id="article_style">
<p>
  <h1><%= @article.title %></h1>
</p>
</div>

 <%= image_tag("desert.jpg", :alt => "image1") %>
<p>
   <%= simple_format @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> 

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Lisa Autz: Writer/Researcher/TEDxOrganizer</h1>
</div>


<h1>Articles</h1>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("desert.jpg", :alt => "image1") %>
      <div class="caption">
        <h3>The Legacy of Desertification In Violent Conflict</h3>
        <p>Perhaps what is most peculiar about the so-called Arab Spring is that it arguably began in Tunisia with a simple fruit vendor desperate to make some money during a record high food price spike</p>
        <a href="../articles/2" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("democracy.jpg", :alt => "image2") %>
      <div class="caption">
        <h3>Uncontested Democracy: New York ballots offer voters startlingly little choice</h3>
        <p>The strength of a democratic government is in its citizens' ability to choose their representatives. But if the choices are limited, is the process truly democratic?</p>
        <p><a href="../articles/3" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>
  <div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("citycouncil.jpg", :alt => "image3") %>
      <div class="caption">
        <h3>The New City Council: What’s Changed and What Hasn’t in 2014</h3>
        <p>Horse carriages, chokeholds, and plastic bags. Legislation on these topics has recently been introduced to the New York City Council and shown marked division among its members.</p>
        <p><a href="../articles/4" class="btn btn-primary" role="button">Read More</a> 
      </div>
    </div>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">LisaAutz.com</br></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to 'Home', home_index_path %></li>
        <li><%= link_to 'Articles', controller: 'articles' %></li>
        <li><%= link_to 'New Article', new_article_path %></li>

        <% if current_user %>
          <li><span><%= current_user.email %></span></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path %> </li>
        <% end %>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPersonalWebsite</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

<div id="app_container">

      <%= yield %>

</div>
    </div>
  </body>
</html>